### ISSUE TITLE
Invalid type of oneOf[].maxItems and oneOf[].minItems

### ISSUE THREAD

**Issue by djusv** [andrewbober/xsd2jsonschema#15]
Hello,
First of all thanks for creating this module so it has worked pretty well in my use case.
But I did find a mismatch with the json schema specification.

* [maxItems  section.6.4.3](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.3) a non negative integer type is expected
* [minItems  section.6.4.4](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.4) a non negative integer type is expected

But currently the output is a string, looking at the code I think the values of `XsdAttributes.MIN_OCCURS` and `XsdAttributes.MAX_OCCURS` should be retrieved as a number in the [converterDraft04.js](https://github.com/andrewbober/xsd2jsonschema/blob/master/src/converterDraft04.js)

**Comment by andrewbober** [comment]
Acknowledged.  I'll update the test case and get it fixed.

Thanks for the feedback!

**Comment by andrewbober** [comment]
This is resolved in version 0.3.5
