### ISSUE TITLE
exclusiveMinimum should be number

### ISSUE THREAD

**Issue by Menshawi** [andrewbober/xsd2jsonschema#16]
Hello Andrew,

Thanks for the great library, its working great.

I found that starting DRAFT 06, `exclusiveMinimum` and `exclusiveMaximum` are supposed to be `number` instead of `boolean`

Thanks,

**Comment by andrewbober** [comment]
Acknowledged.  I'll get if fixed soon.

**Comment by andrewbober** [comment]
This is resolved in version 0.3.5
