### ISSUE TITLE
<Import> tag feature

### ISSUE THREAD

**Issue by anitha-sathish** [andrewbober/xsd2jsonschema#3]
Hello,

Hope the current version of xsd2jsonschema does not support <import> tag  meaning like creating multiples files for each imported schema while converting from xsd to json schema.

When can we expect this feature to be available tentatively? or any workarounds yo can suggest to get it done?

Regards
Anitha

**Comment by andrewbober** [comment]
Hi anitha-sathish,

The \<import\> tag has been implemented in v0.2.1.  The conversion from XML Schema to JSON Schema does preserve the original file count and organization.  For example, if an XML Schema consists of 10 related xsd files the resulting JSON Schema will also contain 10 related files.

Thanks,
Andy
